baseurl = "https://www.example.com"
googleAnalytics = "UA-1740938-12"
languageCode = "en-us"
theme = "hugo-highlights-theme"
title = "Highlights"
[params]
backgroundpersection = true
description = "All about Tammalee"
email = "tammalee@gmail.com"
name = "Tammalee"
[params.footer]
enable = true
[[params.footer.copyright.notice]]
text = "© Untitled"
[[params.footer.copyright.notice]]
text = "Design: [HTML5UP](//html5up.net)"
[[params.footer.copyright.notice]]
text = "Demo Images: [Unsplash](//unsplash.com/)"
[params.footer.social_list]
enable = true
[[params.footer.social]]
icon = "fa-twitter"
link = "https://twitter.com/tammalee"
title = "Twitter"
[[params.footer.social]]
icon = "fa-tumblr"
link = "http://tammalee.tumblr.com"
title = "Tumblr"
[[params.footer.social]]
icon = "fa-instagram"
link = "https://www.instagram.com/tammalee/"
title = "Instagramm"
[[params.footer.social]]
icon = "fa-envelope"
link = "#"
title = "Email"
[params.hero]
buttontext = "Go on..."
description = "Everything you could ever want to know"
title = "Tammalee"
type = "hero"
[[params.block]]
buttontext = "next"
description = "Aliquam ante ac id. Adipiscing interdum lorem praesent fusce pellentesque arcu feugiat. Consequat sed ultricies rutrum. Sed adipiscing eu amet interdum lorem blandit vis ac commodo aliquet integer vulputate phasellus lorem ipsum dolor lorem magna consequat sed etiam adipiscing interdum."
id = "about"
picture = "pic01.jpg"
title = "Who am I"
type = "text"
[[params.block]]
buttontext = "next"
description = "Consequat sed ultricies rutrum. Sed adipiscing eu amet interdum lorem blandit vis ac commodo aliquet vulputate."
id = "skills"
picture = "pic02.jpg"
title = "Stuff I do"
type = "list"
[[params.block.item]]
icon = "fa-camera-retro"
title = "Magna Etiam"
[[params.block.item]]
icon = "fa-pencil"
title = "Lorem Ipsum"
[[params.block.item]]
icon = "fa-code"
title = "Nulla Tempus"
[[params.block.item]]
icon = "fa-coffee"
title = "Sed Feugiat"
[[params.block]]
description = "Aliquam ante ac id. Adipiscing interdum lorem praesent fusce pellentesque arcu feugiat. Consequat sed ultricies rutrum. Sed adipiscing eu amet interdum lorem blandit vis ac commodo aliquet integer vulputate phasellus lorem ipsum dolor lorem magna consequat sed etiam adipiscing interdum."
id = "infos"
picture = "pic03.jpg"
title = "One more thing"
type = "text"
[[params.block]]
id = "contact"
picture = "pic05.jpg"
title = "Get in Touch"
type = "contact"
[params.block.form]
buttontext = "send message"
email = "Your Email"
message = "Your Message"
name = "Name"
