baseurl = "http://go.tammalee.com/"
googleAnalytics = "UA-1740938-12"
languageCode = "en-us"
theme = "hugo-highlights-theme"
title = "Highlights"
[params]
backgroundpersection = true
description = "All about Tammalee"
email = "tammalee@gmail.com"
name = "Tammalee"
[params.footer]
enable = true
[[params.footer.copyright.notice]]
text = "© Untitled"
[[params.footer.copyright.notice]]
text = "Design: [HTML5UP](//html5up.net)"
[[params.footer.copyright.notice]]
text = "Demo Images: [Unsplash](//unsplash.com/)"
[params.footer.social_list]
enable = true
[[params.footer.social]]
icon = "fa-twitter"
link = "https://twitter.com/tammalee"
title = "Twitter"
[[params.footer.social]]
icon = "fa-tumblr"
link = "http://tammalee.tumblr.com"
title = "Tumblr"
[[params.footer.social]]
icon = "fa-instagram"
link = "https://www.instagram.com/tammalee/"
title = "Instagramm"
[params.hero]
buttontext = "Go on..."
description = "Everything you could ever want to know"
title = "Tammalee"
type = "hero"
[[params.block]]
buttontext = "next"
description = "I am a senior web developer specializing in WordPress, education, and mentoring. And eating!"
id = "about"
picture = "/uploads/2018/04/19/autumnleavesbluesky.jpg"
title = "Who am I"
type = "text"
[[params.block]]
buttontext = "next"
description = "I can make up songs, improvise recipes, and make bawdy jokes! Woo! laugh dammit!"
id = "skills"
picture = "pic02.jpg"
title = "Stuff I do"
type = "list"
[[params.block.item]]
icon = "fa-camera-retro"
title = "Magna Etiam"
[[params.block.item]]
icon = "fa-pencil"
title = "Lorem Ipsum"
[[params.block.item]]
icon = "fa-code"
title = "Nulla Tempus"
[[params.block.item]]
icon = "fa-coffee"
title = "Sed Feugiat"
[[params.block]]
description = "All the infos go here!"
id = "infos"
picture = "pic03.jpg"
title = "One more thing"
type = "text"
[[params.block]]
id = "contact"
picture = "pic05.jpg"
title = "Get in Touch"
type = "contact"
[params.block.form]
buttontext = "send message"
email = "Your Email"
message = "Your Message"
name = "Name"
