---
new_page_extension: html
auto_deploy: true
admin_path: admin
webhook_url: ''
sections:
- path: content/posts
  label: Posts
  create: all
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: 0.38.1
